name: .NET Core

on:
  push:
    branches: [ githubactions ]
  pull_request:
    branches: [ githubactions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish with dotnet
      run: dotnet publish --nologo --configuration Release --runtime win-x64 --framework netcoreapp3.0 --no-self-contained --output ./ArtNetTimecodeConsole
    - name: Zip files
      run: zip -r ArtNetTimecodeConsole.zip ./ArtNetTimecodeConsole
